using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.Text.Json.Serialization;
using static ServiceCollectionExtensions;

public class WeatherForecast
{
    public WeatherForecast() { }
    public WeatherForecast(DateTime date, int temperatureC, string? summary)
    {
        Date = date.Date;
        TemperatureC = temperatureC;
        Summary = summary;
    }
    //[JsonConverter(typeof(DateTimeConverterUsingDateTimeParse))]

    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    //We add this attribute as ObjectId is autogenerated so we don't want to show it in Swagger
    [JsonIgnore]
    public string Id { get; set; } = String.Empty;
    public DateTime? Date { get; set; }
    public int TemperatureC { get; set; }
    public string? Summary { get; set; }
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}